###############################################################################
# Makefile for the project qtouch_test
###############################################################################

## General Flags
PROJECT = qtouch_test
MCU = atmega328p
TARGET = qtouch_test.elf

CC = /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc
CPP = /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++
OBJCOPY=/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-objcopy
OBJDUMP=/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-objdump
SIZE=/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-size

## Options common to compile, link and assembly rules
COMMON = -mmcu=$(MCU) 

## Compile options common for all C compilation units.
CFLAGS = $(COMMON)
CFLAGS += -Wall -gdwarf-2 -std=gnu99 -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums
CFLAGS += -MD -MP -MT $(*F).o -MF dep/$(@F).d 

## Assembly specific flags
ASMFLAGS = $(COMMON)
ASMFLAGS += $(CFLAGS)
ASMFLAGS += -x assembler-with-cpp -Wa,-gdwarf2

## Linker flags
LDFLAGS = $(COMMON)
LDFLAGS +=  -Wl,-Map=qtouch_test.map

## Intel Hex file production flags
HEX_FLASH_FLAGS = -R .eeprom -R .fuse -R .lock -R .signature

HEX_EEPROM_FLAGS = -j .eeprom
HEX_EEPROM_FLAGS += --set-section-flags=.eeprom="alloc,load"
HEX_EEPROM_FLAGS += --change-section-lma .eeprom=0 --no-change-warnings

AVRDIR = /Users/theorifice/devel/avr

## Include Directories
INCLUDES = -I../include/

## Library Directories
LIBDIRS = -L../lib/

## Libraries
LIBS = -lavr5g1-4qt-k-0rs 

## Objects that must be built in order to link
OBJECTS = main.o qt_asm_tiny_mega.o uart.o qtouch.o

## Objects explicitly added by the user
LINKONLYOBJECTS = 

## Build
all: $(TARGET) qtouch_test.hex qtouch_test.eep qtouch_test.lss size

## Compile
main.o: main.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

qt_asm_tiny_mega.o: $(AVRDIR)/include/qtouch/common_files/qt_asm_tiny_mega.S
	$(CC) $(INCLUDES) $(ASMFLAGS) -c  $<

uart.o: uart.c
	$(CC) $(INCLUDES) $(CFLAGS) -c $<

qtouch.o: qtouch.c
	$(CC) $(INCLUDES) $(CFLAGS) -c $<

##Link
$(TARGET): $(OBJECTS)
	 $(CC) $(LDFLAGS) $(OBJECTS) $(LINKONLYOBJECTS) $(LIBDIRS) $(LIBS) -o $(TARGET)

%.hex: $(TARGET)
	 $(OBJCOPY) -O ihex $(HEX_FLASH_FLAGS)  $< $@

%.eep: $(TARGET)
	 $(OBJCOPY) $(HEX_EEPROM_FLAGS) -O ihex $< $@ || exit 0

%.lss: $(TARGET)
	 $(OBJDUMP) -h -S $< > $@

size: ${TARGET}
	@echo
	@$(SIZE) -C --mcu=${MCU} ${TARGET}

## Clean target
.PHONY: clean
clean:
	-rm -rf $(OBJECTS) qtouch_test.elf dep/* qtouch_test.hex qtouch_test.eep qtouch_test.lss qtouch_test.map

## Other dependencies
-include $(shell mkdir dep 2>/dev/null) $(wildcard dep/*)

